<?php

namespace AppBundle\Repository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{
    public function fetchUserInfo($email)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a, l
               FROM AppBundle:Address a
               JOIN a.login l
               WHERE l.emailAddress = :email'
        )
            ->setParameter('email', $email);

            return $query->getResult();



    }
    public function getUserInfo($email)
    {

        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT l.id
        FROM AppBundle:Login l
        WHERE l.emailAddress = :email'
        )
            ->setParameter('email', $email);

        // returns an array of Product objects
        return $query->getResult();


    }

    public function getUserAddressId($user_id)
    {

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a.id 
               FROM AppBundle:Address a
               JOIN a.login l
               WHERE l.id = :user_id'
            )
            ->setParameter('user_id', $user_id);

        return $query->getResult();

    }
}
