<?php

namespace AppBundle\Repository;

/**
 * LoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkEmail($email)
    {

        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT l.password
        FROM AppBundle:Login l
        WHERE l.emailAddress = :email'
        )
            ->setParameter('email', $email);

        // returns an array of Product objects
        return $query->getResult();


    }

    public function checkUniqueEmail($email)
    {

        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT l.emailAddress
        FROM AppBundle:Login l
        WHERE l.emailAddress = :email'
        )
            ->setParameter('email', $email);

        // returns an array of Product objects
        return $query->getResult();


    }

    public function getFirstName($email)
    {

        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT l.firstName
        FROM AppBundle:Login l
        WHERE l.emailAddress = :email'
        )
            ->setParameter('email', $email);

        // returns an array of Product objects
        return $query->getResult();


    }

    public function getUserId($email)
    {

        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT l.id
        FROM AppBundle:Login l
        WHERE l.emailAddress = :email'
        )
            ->setParameter('email', $email);

        // returns an array of Product objects
        return $query->getResult();


    }

}
